# -*- coding: utf-8 -*-
"""diabetes-test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jqjirjFEDtIX0DQqdlelAcu-NTylgOhp
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import svm
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression

diab_dtst = pd.read_csv("diabetes.csv")

pd.read_csv?

diab_dtst.head()

diab_dtst.shape

diab_dtst.describe()

diab_dtst["Outcome"].value_counts()

diab_dtst.groupby("Outcome").mean()

X = diab_dtst.drop(columns = "Outcome", axis = 1)
Y = diab_dtst["Outcome"]

print(X)

print(Y)

scalar = StandardScaler()

scalar.fit(X)

standard_dt = scalar.transform(X)

print(standard_dt)

X = standard_dt

Y = diab_dtst["Outcome"]

X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.2, stratify = Y, random_state = 2)

print(X.shape, X_train.shape, X_test.shape)

classifier = svm.SVC(kernel = "linear")

classifier.fit(X_train,Y_train)

X_train_predict = classifier.predict(X_train)
train_dt_acc = accuracy_score(X_train_predict, Y_train)

print(f"The accuracy of training data: {train_dt_acc}")

X_test_predict = classifier.predict(X_test)
test_dt_acc = accuracy_score(X_test_predict, Y_test)

print(f"The accuracy of test data: {test_dt_acc}")

inp_data = (4, 110, 92, 0, 0, 37.6, 0.191, 30)
inp_np_arr = np.asarray(inp_data)
inp_rsp = inp_np_arr.reshape(1,-1)

stan_dt = scalar.transform(inp_rsp)
print(stan_dt)

predict = classifier.predict(stan_dt)
# print(predict)

if predict[0] == 0:
  print("The person is non diabetic")
else:
  print("The person is diabetic")